name: Deploy Next.js to DigitalOcean

on:
  push:
    branches: [main] # Sadece main branch'e push yapınca çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/bgcgroup
            git pull origin main
            npm install
            npm run build
            pm2 restart bgc-app # PM2 isminizle aynı olmalı
